class QuoteOfTheDay {
    constructor() {
        // Obtén la fecha actual
        this.currentDate = new Date();

        // Obtén el día del año (1 al 366)
        this.dayOfTheYear = Math.floor((this.currentDate - new Date(this.currentDate.getFullYear(), 0, 0)) / 86400000);

        console.log("Día del año: " + this.dayOfTheYear);
        this.motivationalQuotes = [
            "Curiosity is the key to discovering the world. - Albert Einstein",
            "Be the change that you wish to see in the world. - Mahatma Gandhi",
            "Knowledge is the only good that increases when shared. - Socrates",
            "Life is what happens when you're busy making other plans. - John Lennon",
            "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
            "The only way to do great work is to love what you do. - Steve Jobs",
            "You can't depend on your eyes when your imagination is out of focus. - Mark Twain",
            "Science is the art of creating possibilities. - Neil deGrasse Tyson",
            "True wisdom is in recognizing one's own ignorance. - Socrates",
            "Every day is an opportunity to learn something new. - Richard Feynman",
            "The journey of a thousand miles begins with one step. - Lao Tzu",
            "In the middle of difficulty lies opportunity. - Albert Einstein",
            "The best way to predict the future is to create it. - Peter Drucker",
            "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
            "It does not matter how slowly you go as long as you do not stop. - Confucius",
            "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
            "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
            "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
            "The harder I work, the luckier I get. - Samuel Goldwyn",
            "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
            "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
            "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
            "Believe you can and you're halfway there. - Theodore Roosevelt",
            "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
            "The best revenge is massive success. - Frank Sinatra",
            "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible. - Joel Brown",
            "You miss 100% of the shots you don't take. - Wayne Gretzky",
            "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
            "Opportunities don't happen. You create them. - Chris Grosser",
            "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
            "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
            "If you can dream it, you can achieve it. - Zig Ziglar",
            "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi",
            "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
            "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
            "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
            "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
            "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
            "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
            "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
            "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
            "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
            "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
            "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
            "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
            "Believe you can and you're halfway there. - Theodore Roosevelt",
            "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
            "The only way to do great work is to love what you do. - Steve Jobs",
            "The harder I work, the luckier I get. - Samuel Goldwyn",
            "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
            "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
            "It does not matter how slowly you go as long as you do not stop. - Confucius",
            "The best way to predict the future is to create it. - Peter Drucker",
            "In the middle of difficulty lies opportunity. - Albert Einstein",
            "The journey of a thousand miles begins with one step. - Lao Tzu",
            "Every day is an opportunity to learn something new. - Richard Feynman",
            "True wisdom is in recognizing one's own ignorance. - Socrates",
            "Science is the art of creating possibilities. - Neil deGrasse Tyson",
            "You can't depend on your eyes when your imagination is out of focus. - Mark Twain",
            "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
            "Life is what happens when you're busy making other plans. - John Lennon",
            "Knowledge is the only good that increases when shared. - Socrates",
            "Be the change that you wish to see in the world. - Mahatma Gandhi",
            "Curiosity is the key to discovering the world. - Albert Einstein",
            "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
            "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
            "The best revenge is massive success. - Frank Sinatra",
            "You miss 100% of the shots you don't take. - Wayne Gretzky",
            "Opportunities don't happen. You create them. - Chris Grosser",
            "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
            "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
            "If you can dream it, you can achieve it. - Zig Ziglar",
            "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi",
            "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
            "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
            "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
            "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
            "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
            "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
            "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
            "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
            "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
            "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
            "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
            "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
        ]
    }
}

window.QuoteOfTheDay = QuoteOfTheDay;
const quoteOfTheDay = new QuoteOfTheDay();